import Header from "@/components/header/Header";

export const metadata = {
  title: "About me",
  description: "Generated by create next app",
};

export default function layout({ children }) {
  return (
    <>
      <Header />
      {children}
    </>
  );
}
