export const metadata = {
    title: "My Projects",
    description: "Generated by create next app",
  };
  
  export default function layout({ children }) {
    return (
        <>
         {children}
        </>
    );
  }